### ISSUE TITLE
Question: is this in the google play store?

### ISSUE THREAD

**Issue by JonasJurczok** [NickToony/PersonalAnxietyTrackerApp#2]
Hi,
this app sounds interesting. Is this still working and if so, is it available in the play store?

Best,
Jonas

**Comment by NickToony** [comment]
Hey,

Afraid not. This code base is very outdated and not maintained in any way. Thanks for the interest though!

Nick

**Comment by JonasJurczok** [comment]
Okay :) Thanks for the quick reply.
